/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utspbo;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Smktelkom
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nopol = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        motor = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        masuk = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        keluar = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel1.setText("OH PARKIR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 10, 290, 30);

        jLabel2.setText("NO resi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 50, 70, 30);
        jPanel1.add(resi);
        resi.setBounds(210, 80, 120, 30);

        jLabel3.setText("NOPOL");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 50, 60, 20);
        jPanel1.add(nopol);
        nopol.setBounds(400, 80, 130, 30);

        jLabel4.setText("JENIS KENDARAAN");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(650, 50, 100, 20);

        buttonGroup1.add(motor);
        motor.setText("Motor");
        jPanel1.add(motor);
        motor.setBounds(630, 80, 53, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Mobil");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(770, 80, 49, 23);
        jPanel1.add(masuk);
        masuk.setBounds(10, 180, 100, 30);

        jLabel5.setText("Tanggal Masuk");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 100, 20);

        jLabel6.setText("Tanggal KELUAR");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 150, 120, 20);
        jPanel1.add(keluar);
        keluar.setBounds(190, 180, 120, 30);

        jLabel7.setText("Harga");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(410, 150, 100, 20);
        jPanel1.add(harga);
        harga.setBounds(400, 180, 140, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 140, 73, 23);

        jButton2.setText("CLEAR");
        jPanel1.add(jButton2);
        jButton2.setBounds(750, 140, 65, 23);

        jButton3.setText("DELETE");
        jPanel1.add(jButton3);
        jButton3.setBounds(630, 190, 69, 23);

        jButton4.setText("PRINT");
        jPanel1.add(jButton4);
        jButton4.setBounds(750, 190, 63, 23);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO RESI", "NOPOL", "JENISKENDARAAN", "TANGGAL MASUK", "TANGGAL KELUAR", "HARGA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 850, 230);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 220, 880, 250);

        jLabel8.setText("Nama penjaga");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 60, 70, 20);
        jPanel1.add(nama);
        nama.setBounds(20, 80, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 470);

        setBounds(0, 0, 892, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String Masuk = dateFormat.format(masuk.getDate());
        String Keluar = dateFormat.format(keluar.getDate());
        String JK ="";
        if(motor.isSelected()){
                    JK = "Motor";
                }else{
                    JK = "MOBIL";
                }
        
        if("".equals(nama.getText()) || "".equals(resi.getText()) || "".equals(nopol.getText()) ||masuk.equals("")|| keluar.equals("") || "".equals(harga.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
        }else {String SQL = "insert into  t_parkir  ('".equals(nama.getText()+"','".equals(resi.getText()+"', '".equals(nopol.getText()+"','"+masuk+"','"+keluar+"'+'".equals(harga.getText());
        int status = KoneksiDB.execute(SQL);
        if(status == 1){
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        }else{
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
                
        
       
    }                                    

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1){
            String NIS = tblData.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }                                      

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        nama.setText("");
        resi.setText("");
        nopol.setText("");
        buttonGroup1.clearSelection();
       
    }                                     

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       ;
    }                                       

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser keluar;
    private com.toedter.calendar.JDateChooser masuk;
    private javax.swing.JRadioButton motor;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nopol;
    private javax.swing.JTextField resi;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
